#配置刷新
POST http://localhost:8301/actuator/bus-refresh

###
GET http://localhost:8402/user/info
Accept: application/json

###

GET http://localhost:8402/user/test
Accept: application/json
cache: false
###

GET http://localhost:8401/key
Accept: application/json
cache: false
###
POST http://localhost:8401/userAuth
cache-control: no-cache
Content-Type: application/json

{
"account":"xujw",
"password":"1320074071"
}
###

POST http://localhost:8201/auth/userAuth
Accept: application/json
cache: false

###

POST http://localhost:8201/auth/open/login/aaaa
Accept: application/json
cache: false
###
POST http://localhost:8201/auth-center/userAuth
cache-control: no-cache
Accept: application/json
Content-Type: application/json

{
  "account":"xujw",
  "password":"1320074071"
}
###
POST http://localhost:8201/auth-center/msg
Accept: application/json
cache: false

###