### 配置刷新
POST {{host-config}}/actuator/bus-refresh

### 用户登录,获取token
POST {{host-auth}}/login
cache-control: no-cache
Content-Type: application/json

{
  "account": "xujw",
  "password": "1320074071"
}

### 带token调用测试

POST {{host-auth}}/client
Accept: application/json
cache: false
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NzEzMDA5NzMsInVzZXIiOiJ4dWp3IiwiaWF0IjoxNTcxMjk5MTczfQ.IMgeQAeQVLBRdJTrLtThRJOi1YU-IMkWQldk7ngulrKUZenG5GDx7dqp3qzAL20Nwq9R2e2WMHYbVPu4-pqJUo06CajcC31FYbEjIGMUVyUKc9OMo7NIbSL45IftFTKpI1nVOS1-ClmzaoeXE11rs_q69Gzlmuu4BiFZxmedWUpUhHM2R20D3WpCQri8jHLCAKnbybowkkRhgMKHDFLnzMwuB2xi_rIogLuWKTGJMi8tgwpCj2QCDY7qPrqKN8G3tPDRbdkHO1f-KfARW9_aPY2yk3GuzxYiwxRH3LJNEmXWtR5jeIYMcOGxCxPi5kOlb3wMGxviHd7JcQKWEkIX9g

### 不带token调用测试
POST {{host-auth}}/client
Content-Type: application/json
cache: false
