server:
  port: 8201
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-center
          #使用lb前缀需要添加ribbon依赖实现负载均衡
          uri: lb://auth-center
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name:AuthFilter
      discovery:
        locator:
          enabled: true #默认会为所有服务都进行转发操作,免去对所有服务进行配置
          lower-case-service-id: true #默认通过网关访问服务id使用大写,通过该配置启用小写服务id
