server:
  port: 8402

spring:
  datasource:
    username: xujw
    password: xujw1320074071
    url: jdbc:mysql://gz-cdb-8z6d9u0o.sql.tencentcdb.com:62542/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
