server:
  port: 8401
msg: hello spring cloud dev
spring:
  datasource:
    auth-center:
      username: xujw
      password: xujw1320074071
      url: jdbc:mysql://cdb-77xksizt.gz.tencentcdb.com:10042/${spring.application.name}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
