# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### 登录
GET http://localhost:8401/doLogin?username=xujw&password=1320
Accept: application/json

### 带token
GET http://localhost:8401/authc/admin
Accept: application/json
cache: false
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOjExODY4NTQ0MjgyMjc2NjE4MjUsImp0aSI6ImViZDEzYzI3LWIzMTQtNDUxNy05YjY5LTNmOWExY2VkNWUyNCIsImlzcyI6Inhqd2NvZGUuY29tIiwiaWF0IjoxNTczMTA4Njg2LCJleHAiOjE1NzMxMTA0ODZ9.i44RhN-d4NospUZSVddecSs3Zlm-QvL2sIsUIUixOB4bUB0A0wi90InE0hYfkHVF3gYZHlO2MDJiT6WxuL32Awx72E5zr--obxC3Sl4z7_jfYtxnRlyflsSYOb9uO4cFYeu3iVhJvIY4ERED7uNCosxLnz5DPPUvdCwuSWEK2_-ZIu8mbj5pKy0g-cNo-QWwd4RoLFDfeYCRx5njwCIekRJ-cjFQev84PI2lXzMp6LEZDLOSvG01Rkw9nA3sf4dzWF1IQ2VElURZI0wziq4lvvNF2-DWXb0W83C8IvhBLKbSGvQZZdR8paiLtSEZOHdE9WtfO4MS6bUQUJSwqJ6zfA

### 不带token
GET http://localhost:8401/authc/admin
Accept: application/json
cache: false

### 开放路径
GET http://localhost:8401/unauthc
Accept: application/json
cache: false

###
