#Eureka单节点配置
server:
  port: 8104
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #必须配置否则会报错,在集群模式下填写其他eureka节点地址,单机模式下填自身地址
      defaultZone: http://localhost:8104/eureka/
    ###是否注册到eureka,集群模式下为ture,单机模式下false
    register-with-eureka: false
    ###集群模式下一定要设置为true或者不写，否则会出现unavailable-replicas,单机模式下false
    fetch-registry: false
