spring:
  application:
    name: eureka-server
  profiles:
    #通过多配置实现单机集群模拟
    #      active: server1
    #      active: server2
    #      active: server3
    active: server4
# 配置eureka用户名密码
  security:
    user:
      name: xujw
      password: 1320074071
