#Eureka单节点配置
server:
  port: 8101
eureka:
  instance:
    # 需要远程连接时需配置公网ip
    ip-address: 106.12.48.228
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      #必须配置否则会报错,在集群模式下填写其他eureka节点地址,单机模式下填自身地址
      defaultZone: http://localhost:8101/eureka/
    ###是否注册到eureka,集群模式下为ture,单机模式下false
    register-with-eureka: false
    ###是否拉取服务注册表,集群模式下一定要设置为true或者不写，否则会出现unavailable-replicas,单机模式下false
    fetch-registry: false
