# 基础公共配置文件
env: dev
base: base-config-dev-reflash
logging:
  level: debug
  path: /logs/${spring.application.name}
  file: ${spring.application.name}.log
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
