# 基础公共配置文件
env: prod
logging:
  root:
    level: WARN
  file: ../logs/${spring.application.name}.log
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
