# 基础公共配置文件
env: dev
base: base-config-dev-reflash22
eureka:
  client:
    service-url:
      defaultZone: http://server01:8101/eureka/,http://server02:8102/eureka/,http://server03:8103/eureka/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
