# 基础公共配置文件
env: dev
base: base-config-dev
#通过消息服务自动刷新配置
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
